### ISSUE TITLE
Update module name

### ISSUE THREAD

**Issue by lovromazgon** [conduitio-labs/conduit-connector-bigquery#1]
The [module name](https://github.com/conduitio-labs/conduit-connector-bigquery/blob/f3f3740099b48e174f9d02703c7b2fe9459a2498/go.mod#L1) should be `github.com/conduitio-labs/conduit-connector-bigquery`, also search and update any references in the code to the module (e.g. I found [this import](https://github.com/conduitio-labs/conduit-connector-bigquery/blob/f3f3740099b48e174f9d02703c7b2fe9459a2498/cmd/connector/main.go#L20)).

**Comment by alyakimenko** [comment]
Resolved in https://github.com/conduitio-labs/conduit-connector-bigquery/pull/2.
